# 顾客库
customer-master:
  datasource:
    url: jdbc:mysql://localhost:3306/prd_customer?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  #门店库
store-master:
  datasource:
    url: jdbc:mysql://localhost:3306/prd_store?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver