# 顾客库
master:
  datasource:
    url: jdbc:mysql://localhost:3306/prd_customer?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  #门店库
cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/prd_store?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
  dubbo:
    application:
      id: customer-api
      name: live-dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181
  server: true
  protocol:
    name: dubbo
    port: 20880
server:
  port: 8088

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


  ## dubbo springboot 配置



